# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-0K16M9BQP7'

menu:
- {name: 'About Me',  url: 'about-me'}
# - {name: 'Learning Resources', url: 'resources'}
- {name: 'League Clips',       url: 'league-clips'}
- {name: 'Writing Work',      url: 'writing-work'}
#- {name: 'About',              url: 'about'}
#- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link:    ''}
# - {icon: 'facebook', link:   ''}
- {icon: 'instagram', link:  'https://instagram.com/ethanyzhang21/'}
- {icon: 'envelope', link:   'mailto:ethanzhang21.az@gmail.com'}
# - {icon: 'rss-square', link: ''}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
